### ISSUE TITLE
Working with Sea Ice Concentration Data

### ISSUE THREAD

**Issue by ronygolderku** [polarwatch/code-gallery#7]
Hi there,
I am Rony. Thanks for making this awsome repository.
While exploring the contents of the repository [[working-with-sea-ice-conc-data/working-with-sea-ice-conc-data.ipynb](https://github.com/polarwatch/code-gallery/blob/main/working-with-sea-ice-conc-data/working-with-sea-ice-conc-data.ipynb)], I noticed that the dataset dimensions `ygrid` and `xgrid` are represented in metres/kilometers.

I am particularly interested in learning how to crop/slice the sea ice dataset based on latitude and longitude coordinates. Given that the dataset utilizes `ygrid`' and `xgrid` dimensions, I would like to understand the process of clipping (cropping) the dataset using latitude and longitude coordinates. Alternatively, if possible, I would also like to explore the option of using a shapefile for cropping purposes.

Thank you for your time and assistance.

Rony

**Comment by shospital** [comment]
Hello Rony,

We are currently working on R code sample to subset projected data using shape files.  We will also create python version as well. 
We will keep you posted once they are ready on the github repository!
